/* automatically generated by rust-bindgen 0.69.4 */

extern "C" {
    pub static mut stop_dimension: ::std::os::raw::c_int;
}
extern "C" {
    pub fn fpli_hv(
        data: *mut f64,
        d: ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
        ref_: *const f64,
    ) -> f64;
}
