name: Release on crate.io

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crate:
    name: Cargo publish
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: cargo publish --verbose -p optirustic